#!/usr/bin/env bash
# script to configure broken container to work with nginx at port 8080
# restart nginx as nginx user
wget -O do_fix https://raw.github.com/1923k/alx-system_engineering-devops/blob/master/0x12-web_stack_debugging_2/100-backer
chmod u+x do_fix
./do_fix
